Adapt to SnoopCompile v3
julia-actions/julia-invalidations pull request #21
Opened 2024-07-24 18:48 UTC by schillic

Closes #18 (I think).

The fix was pretty simple: `@snoopr` was renamed to `@snoop_invalidations` (see [NEWS.md](https://github.com/timholy/SnoopCompile.jl/blob/master/NEWS.md#version-3)).

2024-07-24 21:18 UTC, fingolfin commented
But the new version requires Julia 1.10. We don't control which Julia version is used to execute this action, do we? Of course the recommended usage example in README suggests to use
```
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1'
```
So perhaps follows that and we are fine?

2024-07-25 08:02 UTC, DilumAluthge commented
It seems like the immediate fix should be to modify the `Pkg.add` statement in this action to install SnoopCompile v2, right? Then this won't have any impact on the Julia version compatibility.

2024-07-25 08:09 UTC, DilumAluthge commented
I think we should do https://github.com/julia-actions/julia-invalidations/pull/22 as the immediate fix.

2024-07-25 08:22 UTC, DilumAluthge requested changes
I think we should first do https://github.com/julia-actions/julia-invalidations/pull/22 as the immediate fix.

2024-07-25 08:31 UTC, schillic commented
Fair enough. Thanks for the quick fix!

2024-07-25 08:31 UTC, closed without merging

2024-07-25 08:35 UTC, schillic commented
Note that the link to `@snoopr` in the README is still broken.

2024-07-25 09:17 UTC, DilumAluthge commented
> Note that the link to `@snoopr` in the README is still broken.

Good catch! #29